import React, { useState, useMemo, useEffect, ErrorInfo, ReactNode } from 'react';
import {
    Users,
    Settings,
    ChevronDown,
    LogOut,
    Building2,
    PieChart,
    Truck,
    Database,
    ChevronLeft,
    ChevronRight,
    Filter,
    Eye,
    EyeOff
  } from 'lucide-react';
import DriverTable from './components/DriverTable';
import DispatcherTable from './components/DispatcherTable';
import FranchiseTable from './components/FranchiseTable';
import SettingsView from './components/SettingsView';
import PnLView from './components/PnLView';
import { COMPANY_FIXED_EXPENSES, DEFAULT_SIMULATION_CONFIG } from './constants';
import { UserRole, SimulationConfig, DriverPerformance, ExpenseItem, DriverStatus, SupabaseDriverRecord, FinImportRecord, ConfigContract } from './types';
import { supabase, isSupabaseConfigured, fetchFixedExpenses, saveFixedExpenses, fetchConfigContracts } from './lib/supabase';

interface ErrorBoundaryProps {
  children?: ReactNode;
}

interface ErrorBoundaryState {
  hasError: boolean;
  error: Error | null;
}

// Simple Error Boundary to catch runtime crashes
class ErrorBoundary extends React.Component<ErrorBoundaryProps, ErrorBoundaryState> {
  constructor(props: ErrorBoundaryProps) {
    super(props);
    this.state = { hasError: false, error: null };
  }

  static getDerivedStateFromError(error: Error): ErrorBoundaryState {
    return { hasError: true, error };
  }

  componentDidCatch(error: Error, errorInfo: ErrorInfo) {
    console.error("Uncaught error:", error, errorInfo);
  }

  render() {
    if (this.state.hasError) {
      return (
        <div className="min-h-screen bg-zinc-950 flex flex-col items-center justify-center text-zinc-300 p-4 font-sans">
          <div className="bg-zinc-900 p-6 rounded-lg border border-zinc-800 max-w-md w-full shadow-2xl">
            <h2 className="text-xl font-bold text-white mb-2">Something went wrong</h2>
            <p className="text-sm text-zinc-500 mb-4">The application encountered an error while rendering.</p>
            <div className="bg-black/50 p-3 rounded text-xs font-mono text-rose-400 mb-6 overflow-auto max-h-32">
              {this.state.error?.message || "Unknown Error"}
            </div>
            <button 
              onClick={() => { localStorage.clear(); window.location.reload(); }}
              className="w-full py-2 bg-emerald-600 hover:bg-emerald-500 text-white rounded font-medium transition-colors text-sm"
            >
              Reset App Data & Reload
            </button>
          </div>
        </div>
      );
    }
    return this.props.children;
  }
}
const APP_START_TIME = Date.now();
const LOADING_TIPS = [
  "You can watch video tutorials in the Help section to learn more about the platform features.",
  "Use the Simulator to project revenue splits and net pay for all contract types.",
  "Weekly expenses can be tracked and displayed accurately per individual truck.",
  "Configure custom financial rules and splits per contract type, company, or specific team.",
  "Use the Global Filter to narrow down financial data by Franchise, Company, Team, or Driver.",
  "The Dashboard displays real-time fuel savings and precise toll calculations.",
  "Easily sync large logistics datasets seamlessly to the database.",
  "Switch to the Drivers tab to analyze individual performance metrics and historical trends.",
  "Negative escrow balances are tracked and can be automatically deducted during settlements.",
  "Review the Master Operating Statement for a comprehensive view of administrative financials.",
  "Compare actual earnings versus simulated net pay across different dispatching divisions.",
  "Fixed and variable deductions like IFTA, ELD, and maintenance are fully automated.",
  "Monitor fleet-wide average MPG to pinpoint inefficiencies and optimize fuel consumption.",
  "Track recruiting costs, effective trailer counts, and overall equipment efficiency.",
  "The Dispatchers tab provides insight into profitability and margins generated by each dispatcher.",
  "Export or review historical snapshots to maintain accurate records of past pay periods.",
  "Company-wide fixed expenses can be updated dynamically in the Settings.",
  "Role-based access ensures Franchise dispatchers only see data relevant to their operation.",
  "Review specific truck float, liability, and maintenance support deductions per driver.",
  "Ensure historical accuracy by managing historical data in the snapshots architecture."
];
const getSyncedTip = () => Math.floor((Date.now() - APP_START_TIME) / 1000) % LOADING_TIPS.length;
const LoadingScreen = ({ progress }: { progress: number }) => {
  const [animDelays] = useState(() => {
    const elapsed = (Date.now() - APP_START_TIME) / 1000;
    return { d10: `-${elapsed % 10}s`, d14: `-${elapsed % 14}s`, d18: `-${elapsed % 18}s` };
  });
  const [displayProgress, setDisplayProgress] = useState(0);
  const [activeTip, setActiveTip] = useState(() => Math.floor(Math.random() * LOADING_TIPS.length));

  const tips = LOADING_TIPS;

  useEffect(() => {
    const tipInterval = setInterval(() => {
      setActiveTip(prev => (prev + 1) % tips.length);
    }, 2500);
    return () => clearInterval(tipInterval);
  }, []);

  useEffect(() => {
    if (progress === 100) {
      setDisplayProgress(100);
      return;
    }
    const timer = setInterval(() => {
      setDisplayProgress(prev => {
        if (prev >= 100) return 100;
        if (prev < progress) return prev + Math.max(1, Math.floor((progress - prev) / 4));
        return prev;
      });
    }, 15);
    return () => clearInterval(timer);
  }, [progress]);
  const activeBlocks = Math.floor((displayProgress / 100) * 40);

  return (
    <div className="fixed inset-0 z-50 flex flex-col items-center justify-center bg-gradient-to-br from-black via-[#020a06] to-black overflow-hidden">
      <div className="absolute inset-0 bg-[linear-gradient(to_right,#10b98108_1px,transparent_1px),linear-gradient(to_bottom,#10b98108_1px,transparent_1px)] bg-[size:40px_40px]"></div>
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[900px] h-[900px] bg-emerald-800/15 rounded-full blur-[150px] pointer-events-none"></div>
      <div className="absolute top-[5%] left-[5%] w-[600px] h-[600px] bg-purple-700/15 rounded-full blur-[120px] pointer-events-none"></div>
      <div className="absolute bottom-[5%] right-[5%] w-[600px] h-[600px] bg-blue-700/15 rounded-full blur-[120px] pointer-events-none"></div>

      <div className="w-64 h-64 mb-16 relative flex items-center justify-center">
        <div className="absolute inset-6 bg-emerald-500/5 rounded-full blur-2xl animate-pulse"></div>
        <div className="absolute inset-0 border-[2px] border-emerald-500/10 border-t-emerald-500/80 border-b-emerald-500/80 rounded-[2rem] animate-[spin_10s_linear_infinite]" style={{ animationDelay: animDelays.d10 }}></div>
        <div className="absolute inset-3 border-[2px] border-blue-500/10 border-l-blue-500/80 border-r-blue-500/80 rounded-3xl animate-[spin_14s_linear_infinite_reverse]" style={{ animationDelay: animDelays.d14 }}></div>
        <div className="absolute inset-6 border-[2px] border-indigo-500/10 border-t-indigo-500/80 border-b-indigo-500/80 rounded-2xl animate-[spin_18s_linear_infinite]" style={{ animationDelay: animDelays.d18 }}></div>
        <img src="https://i.postimg.cc/ryjhgvGq/Default-Make-a-logo-for-Profit-and-Loss-application-portal-It-2-a128667d-b54d-44ca-bb4d-32ac1ddb5c95.png" alt="PnL Logo" className="w-48 h-48 object-contain drop-shadow-[0_0_30px_rgba(16,185,129,0.4)] z-10" referrerPolicy="no-referrer" />
      </div>
      
      <div className="w-[500px] z-10 mb-12">
        <div className="flex justify-between items-end mb-3 font-mono text-[10px] tracking-[0.2em] text-emerald-500/70">
          <span className="text-emerald-500/60 font-bold uppercase">Loading...</span>
          <span className="text-emerald-400 text-xl font-medium leading-none">{displayProgress}<span className="text-emerald-500/50 text-sm">%</span></span>
        </div>
        <div className="flex gap-1 h-2">
           {Array.from({ length: 40 }).map((_, i) => (
              <div key={i} className={`h-full flex-1 rounded-sm ${i < activeBlocks ? 'bg-[#10b981] shadow-[0_0_10px_#10b981]' : 'bg-zinc-800/40'}`} />
           ))}
        </div>
      </div>

      <div className="absolute bottom-16 w-3/4 max-w-lg text-center z-10">
        <div className="h-12 text-sm text-zinc-400 font-light tracking-wide px-4 leading-relaxed">"{tips[activeTip]}"</div>
        <div className="flex justify-center gap-2.5 mt-8">
          {tips.map((_, idx) => (
            <div key={idx} className={`w-1.5 h-1.5 rounded-full transition-all duration-500 ${activeTip === idx ? 'bg-emerald-400 w-8 shadow-[0_0_8px_#34d399]' : 'bg-zinc-800'}`} />
          ))}
        </div>
      </div>
    </div>
  );
};

const HARDCODED_DISPATCHER_TIERS = [
  { id: '1', tier_name: 'STARTING', min_tpog_percent: 0, max_tpog_percent: 25, dispatcher_share_percent: 0.5, company_share_percent: 0.5, valid_from: '2020-01-01' },
  { id: '2', tier_name: 'MIDDLE', min_tpog_percent: 25, max_tpog_percent: 32, dispatcher_share_percent: 0.75, company_share_percent: 0.25, valid_from: '2020-01-01' },
  { id: '3', tier_name: 'STREAK', min_tpog_percent: 32, max_tpog_percent: 999, dispatcher_share_percent: 1, company_share_percent: 0, valid_from: '2020-01-01' }
];

const HARDCODED_GLOBAL_RULES = [
  { id: '1', dispatcher_base_gross_percent: 2.0, dispatcher_base_margin_percent: 20.0, franchise_split_percent: 50.0, valid_from: '2020-01-01' }
];

const AppContent: React.FC<{ session: any }> = ({ session }) => {
  const [currentRole, setCurrentRole] = useState<UserRole>(UserRole.ADMIN);
  const [activeTab, setActiveTab] = useState<'financials' | 'drivers' | 'dispatchers' | 'franchises' | 'settings'>('financials');
  
  // Unified Filter State: "ALL" | "CMP:id" | "FR:id" | "TM:id"
  const [globalFilter, setGlobalFilter] = useState<any>({ contracts: [], franchises: [], companies: [], teams: [], drivers: [] });
  const [isSidebarCollapsed, setSidebarCollapsed] = useState(false);
  
  // -- STATE MANAGEMENT --
  
  // 1. Simulation Config (Safe Load)
  const [simulationConfig, setSimulationConfig] = useState<SimulationConfig>(() => {
    try {
      const saved = localStorage.getItem('tpog_sim_config');
      return saved ? JSON.parse(saved) : DEFAULT_SIMULATION_CONFIG;
    } catch (e) {
      return DEFAULT_SIMULATION_CONFIG;
    }
  });

  // 2. Fixed Expenses (Init with constants, then fetch from DB)
  const [fixedExpenses, setFixedExpenses] = useState<ExpenseItem[]>(COMPANY_FIXED_EXPENSES);
  
  const [configContracts, setConfigContracts] = useState<ConfigContract[]>([]);
 

  const [rawDrivers, setRawDrivers] = useState<Partial<DriverPerformance>[]>([]);
  const [finImportData, setFinImportData] = useState<FinImportRecord[]>([]);
  const [fixedCostsData, setFixedCostsData] = useState<any[]>([]);
  
  const [isConnected, setIsConnected] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [loadingProgress, setLoadingProgress] = useState(0);
  const [lastUpdated, setLastUpdated] = useState<Date>(new Date());
  const [isDashboardReady, setIsDashboardReady] = useState(false);

  // -- EFFECTS --
  
  useEffect(() => {
    localStorage.setItem('tpog_sim_config', JSON.stringify(simulationConfig));
  }, [simulationConfig]);

  

  // Save handler passed down to Modal
  const handleSaveExpenses = async (newExpenses: ExpenseItem[]) => {
    setFixedExpenses(newExpenses);
    if (isSupabaseConfigured()) {
      await saveFixedExpenses(newExpenses);
    }
  };

  const fetchLock = React.useRef(false);

  const fetchData = async (silent: boolean = false) => {
        if (fetchLock.current) return;
        
        if (!isSupabaseConfigured()) {
          setIsConnected(false);
          if (!silent) setIsLoading(false);
          return;
        }

        fetchLock.current = true;
        if (!silent) {
            setIsLoading(true);
            setLoadingProgress(2);
        }
        try {
          let allData: any[] = [];
          const limit = 10000;
          let from = 0;

          const { count } = await supabase
            .from('pnl_secure_view')
            .select('*', { count: 'exact', head: true });
          const totalRecords = count || 1;
          setLoadingProgress(10);

          while (true) {
            const { data, error } = await supabase
              .from('pnl_secure_view')
              .select('*')
              .order('pay_date', { ascending: false })
              .order('driver_name', { ascending: true })
              .range(from, from + limit - 1);

            if (error) {
              break;
            }

            if (data && data.length > 0) {
              allData.push(...data);
              setLoadingProgress(10 + Math.round((allData.length / totalRecords) * 40));
              if (data.length < limit) break;
              from += limit;
            } else {
              break;
            }
          }

          let loadedPromises = 0;
          const tickPromise = () => {
             loadedPromises++;
             setLoadingProgress(50 + (loadedPromises * 10));
          };

          const confContractsPromise = fetchConfigContracts().then(res => { tickPromise(); return res; });
          const fixedExpensesPromise = fetchFixedExpenses().then(res => { tickPromise(); return res; });
          const finResPromise = supabase.from('finImport').select('*').limit(1000).then(res => { tickPromise(); return res; });
          const fixedCostsPromise = supabase.from('fixed_costs').select('*').order('pay_date', { ascending: false }).then(res => { tickPromise(); return res; });

          const [finRes, confC, dbExpenses, fixedCostsRes] = await Promise.all([
            finResPromise,
            confContractsPromise,
            fixedExpensesPromise,
            fixedCostsPromise
          ]);
      
      if (fixedCostsRes && fixedCostsRes.data) {
        setFixedCostsData(fixedCostsRes.data);
      }

      setConfigContracts(confC);
      if (dbExpenses && dbExpenses.length > 0) {
         setFixedExpenses(dbExpenses);
      }

      if (finRes.data) {
        setFinImportData(finRes.data as FinImportRecord[]);
      }
      
      setLoadingProgress(100);
      await new Promise(resolve => setTimeout(resolve, 10));

      if (allData.length > 0) {
        setIsConnected(true);
        
        const mappedDrivers: Partial<DriverPerformance>[] = allData.map((row: any) => {
          const dbCalculatedFixed = 0;
          
          return {
            id: row.contract_id || String(Math.random()),
            name: row.driver_name,
            companyId: row.company_name || 'UNRECONCILED',
            contractType: row.contract_type || 'Unassigned',
            contract_calc: row.contract_calc,
            franchiseId: row.franchise_name,
            dispatcherId: row.stub_dispatcher,
            teamId: row.stub_team,
            status: String(row.status || '').toLowerCase().trim().includes('term') ? DriverStatus.TERMINATED : DriverStatus.ACTIVE,
            weeksActive: 1,
            streakWeeks: 0,
            payDate: row.pay_date,
            milesDriven: Number(row.total_miles) > 0 ? Number(row.total_miles) : 0,
            grossRevenue: Number(row.driver_gross || 0),
            totalGross: Number(row.driver_gross || 0) + Number(row.margin || 0),
            grossPay: 0,
            companyPay: Number(row.revenue_collected || 0),
            marginAmount: Number(row.margin || 0),
            calculatedFixedCost: dbCalculatedFixed,
             fixed_costs: Number(row.fixed_costs || 0),
              fuelSavings: Number(row.fuel_saved || 0),
              spotter_fuel_saved: Number(row.spotter_fuel_saved || 0),
              fuel_saved: Number(row.fuel_saved || 0),
              franchise_revenue_collected: Number(row.franchise_revenue || 0),
              franchise_po: Number(row.franchise_po || 0),
              baseFuelCost: 0,
            tollCost: Number(row.tolls_amount || 0) !== 0 ? -Math.abs(Number(row.tolls_amount || 0)) : 0,
             baseMaintenanceCost: 0,
             baseDriverFaultExpenses: 0,
             netPay: Number(row.net_pay || 0),
             fuelUsed: 0,
             fuel_quantity: row.fuel_quantity ? Number(String(row.fuel_quantity).replace(/,/g, '')) : 0,
             fuelCost: Number(row.fuel_spent || 0),
            tollCost: Number(row.tolls_amount || 0) !== 0 ? -Math.abs(Number(row.tolls_amount || 0)) : 0,
            maintenanceCost: 0,
            driverFaultExpenses: 0,
            escrowBalance: Number(row.escrow_needed || 0),
            negativeBalance: Number(row.balance || 0) < 0 ? Number(row.balance) : 0,
            poAmount: 0,
            poCoverage: Number(row.total_po_comp_covered || 0),
            driverPoCoverage: Number(row.total_po_comp_covered || 0),
            po_breakdown: typeof row.po_breakdown === 'string' ? (()=>{try{return JSON.parse(row.po_breakdown);}catch(e){return {};}})() : (row.po_breakdown || {}),
            franchise_po_breakdown: typeof row.franchise_po_breakdown === 'string' ? (()=>{try{return JSON.parse(row.franchise_po_breakdown);}catch(e){return {};}})() : (row.franchise_po_breakdown || {}),
            balanceTotal: Number(row.balance || 0),
            recruitingCost: Number(row.recruiting || 0),
            effectiveDrivers: Number(row.effective_drivers || 0),
            effectiveNonTeams: Number(row.eff_non_teams || 0),
            effectiveTrailers: Number(row.eff_trailers || 0),
            numOfTrucks: Number(row.num_of_trucks || 0),
            avgTruckPrice: Number(row.avg_truck_price || 0),
            pnl4wSum: Number(row.pnl_4w_sum || 0),
            pnl4wAvg: Number(row.pnl_4w_avg || 0),
            revenue_base: Number(row.revenue_base || 0),
            po_deductions: Number(row.po_deductions || 0),
            po_settle: Number(row.po_settle || 0),
            balance_settle: Number(row.balance_settle || 0),
            truck_float: Number(row.truck_float || 0),
            truck_wkly: Number(row.truck_wkly || 0),
            occ_ins: Number(row.occ_ins || 0),
            eld: Number(row.eld || 0),
            ifta: Number(row.ifta || 0),
            maintenance_support: Number(row.maintenance_support || 0),
            liability: Number(row.liability || 0),
            truck_phd: Number(row.truck_phd || 0),
            trailer: Number(row.trailer || 0),
            trailer_phd: Number(row.trailer_phd || 0),
            escrowDeduct: Number(row.escrow_deduct || 0),
            tolls: Number(row.tolls || 0),
            cashAdvancePercent: Number(row.cash_advance_percent || 0),
            revenueCpm: Number(row.revenue_cpm || 0),
            revWithoutFuel: Number(row.rev_without_fuel || 0),
            franchiseRevCappedBal: Number(row.franchise_rev_capped_bal || 0)
          };
        });

        const validDates = new Set();
        mappedDrivers.forEach(d => {
          if (d.companyPay && Math.abs(d.companyPay) > 0) {
            validDates.add(d.payDate);
          }
        });
        
        setRawDrivers(mappedDrivers.filter(d => validDates.has(d.payDate)));
      } else {
        setIsConnected(false);
      }
    } catch (err) {
      setIsConnected(false);
    } finally {
      if (!silent) setIsLoading(false);
      setLastUpdated(new Date());
      fetchLock.current = false;
    }
  };
  useEffect(() => {
    fetchData();

    if (!isSupabaseConfigured()) return;

    const realtimeChannel = supabase
      .channel('app-realtime')
      .on('postgres_changes', { event: '*', schema: 'public', table: 'pnl_secure_view' }, () => {
        fetchData(true);
      })
      .on('postgres_changes', { event: '*', schema: 'public', table: 'finImport' }, () => {
        fetchData(true);
      })

    return () => {
      supabase.removeChannel(realtimeChannel);
    };
  }, []);

  const simulatedDrivers = useMemo(() => {
    return rawDrivers as DriverPerformance[];
  }, [rawDrivers]);

  // Extract unique lists for Dropdown
  

  const uniqueFranchises = useMemo(() => 
    Array.from(new Set(simulatedDrivers.map(d => d.franchiseId))).filter(Boolean).sort(),
  [simulatedDrivers]);

  const uniqueCompanies = useMemo(() => 
    Array.from(new Set(simulatedDrivers.map(d => d.companyId))).filter(Boolean).sort(),
  [simulatedDrivers]);

  const uniqueTeams = useMemo(() => 
    Array.from(new Set(simulatedDrivers.map(d => d.teamId))).filter(Boolean).sort(),
  [simulatedDrivers]);

  // 2. Filter Logic
  const filteredDrivers = useMemo(() => {
    let drivers = simulatedDrivers;

    if (globalFilter?.contracts?.length > 0) {
      drivers = drivers.filter(d => d.contractType && globalFilter.contracts.includes(d.contractType));
    }
    if (globalFilter?.franchises?.length > 0) {
      drivers = drivers.filter(d => d.franchiseId && globalFilter.franchises.includes(d.franchiseId));
    }
    if (globalFilter?.companies?.length > 0) {
      drivers = drivers.filter(d => d.companyId && globalFilter.companies.includes(d.companyId));
    }
    if (globalFilter?.teams?.length > 0) {
      drivers = drivers.filter(d => d.teamId && globalFilter.teams.includes(d.teamId));
    }
    if (globalFilter?.drivers?.length > 0) {
      drivers = drivers.filter(d => d.name && globalFilter.drivers.includes(d.name));
    }

    if (currentRole === UserRole.FRANCHISE) {
      drivers = drivers.filter(d => d.franchiseId === 'FR-01'); 
    }
    return drivers;
  }, [globalFilter, currentRole, simulatedDrivers]);

  const latestPayDate = useMemo(() => {
    const dates = Array.from(new Set(simulatedDrivers.map(d => d.payDate).filter(Boolean)));
    return dates.sort((a, b) => new Date(b as string).getTime() - new Date(a as string).getTime())[0] || null;
  }, [simulatedDrivers]);

  const currentWeekDrivers = useMemo(() => {
    if (!latestPayDate) return filteredDrivers;
    return filteredDrivers.filter(d => d.payDate === latestPayDate);
  }, [filteredDrivers, latestPayDate]);

  const showLoading = isLoading || (activeTab === 'financials' && !isDashboardReady && rawDrivers.length > 0);

  return (
    <>
      {showLoading && <LoadingScreen progress={isLoading ? loadingProgress : 100} />}
      <div className={`flex h-screen bg-zinc-950 text-zinc-300 font-sans overflow-hidden text-xs ${showLoading ? 'opacity-0 absolute inset-0 pointer-events-none' : ''}`}>
      
      {/* Sidebar - Collapsible */}
      <aside 
        className={`${isSidebarCollapsed ? 'w-20' : 'w-60'} border-r border-zinc-800 flex flex-col justify-between transition-all duration-300 flex-shrink-0 bg-zinc-950`}
      >
        <div>
          <div className={`h-20 flex items-center ${isSidebarCollapsed ? 'justify-center' : 'justify-start px-4'} border-b border-zinc-800 relative overflow-hidden`}>
            <div className={`flex items-center justify-center relative ${isSidebarCollapsed ? 'w-10 h-10' : 'w-14 h-14 ml-1'}`}>
              <div className="absolute inset-[1px] border-[1px] border-emerald-500/20 border-t-emerald-500/80 border-b-emerald-500/80 rounded-xl animate-[spin_10s_linear_infinite]"></div>
              <div className="absolute inset-[2px] border-[1px] border-blue-500/20 border-l-blue-500/80 border-r-blue-500/80 rounded-lg animate-[spin_14s_linear_infinite_reverse]"></div>
              <div className="absolute inset-[3px] border-[1px] border-indigo-500/20 border-t-indigo-500/80 border-b-indigo-500/80 rounded-md animate-[spin_18s_linear_infinite]"></div>
              <img src="https://i.postimg.cc/ryjhgvGq/Default-Make-a-logo-for-Profit-and-Loss-application-portal-It-2-a128667d-b54d-44ca-bb4d-32ac1ddb5c95.png" alt="PnL Logo" className={`${isSidebarCollapsed ? 'w-14 h-14' : 'w-20 h-20'} absolute object-contain drop-shadow-lg z-10`} referrerPolicy="no-referrer" />
            </div>
            
            <button 
              onClick={() => setSidebarCollapsed(!isSidebarCollapsed)}
              className={`text-zinc-500 hover:text-white transition-colors absolute right-3 ${isSidebarCollapsed ? 'hidden' : 'block'}`}
            >
              {isSidebarCollapsed ? <ChevronRight size={14} /> : <ChevronLeft size={14} />}
            </button>
          </div>

          <nav className="p-2 space-y-0.5">
             {/* Mobile/Collapsed Toggle Button if needed at top */}
             {isSidebarCollapsed && (
               <button 
                onClick={() => setSidebarCollapsed(false)}
                className="w-full flex items-center justify-center p-2 mb-2 text-zinc-500 hover:text-white"
               >
                 <ChevronRight size={14} />
               </button>
             )}

            {currentRole !== UserRole.DISPATCHER && (
              <button 
                onClick={() => setActiveTab('financials')}
                className={`w-full flex items-center ${isSidebarCollapsed ? 'justify-center p-2' : 'p-2 px-3'} rounded transition-all ${activeTab === 'financials' ? 'bg-zinc-800 text-white shadow-inner' : 'hover:bg-zinc-900/50 text-zinc-500'}`}
                title="Financials"
              >
                <PieChart size={16} />
                {!isSidebarCollapsed && <span className="ml-3 font-medium">Financials</span>}
              </button>
            )}

            <button 
              onClick={() => setActiveTab('drivers')}
              className={`w-full flex items-center ${isSidebarCollapsed ? 'justify-center p-2' : 'p-2 px-3'} rounded transition-all ${activeTab === 'drivers' ? 'bg-zinc-800 text-white shadow-inner' : 'hover:bg-zinc-900/50 text-zinc-500'}`}
              title="Drivers"
            >
              <Truck size={16} />
              {!isSidebarCollapsed && <span className="ml-3 font-medium">Drivers</span>}
            </button>
            
            <button 
              onClick={() => setActiveTab('dispatchers')}
              className={`w-full flex items-center ${isSidebarCollapsed ? 'justify-center p-2' : 'p-2 px-3'} rounded transition-all ${activeTab === 'dispatchers' ? 'bg-zinc-800 text-white shadow-inner' : 'hover:bg-zinc-900/50 text-zinc-500'}`}
              title="Dispatchers"
            >
              <Users size={16} />
              {!isSidebarCollapsed && <span className="ml-3 font-medium">Dispatchers</span>}
            </button>
            
            <button 
              onClick={() => setActiveTab('franchises')}
              className={`w-full flex items-center ${isSidebarCollapsed ? 'justify-center p-2' : 'p-2 px-3'} rounded transition-all ${activeTab === 'franchises' ? 'bg-zinc-800 text-white shadow-inner' : 'hover:bg-zinc-900/50 text-zinc-500'}`}
              title="Franchises"
            >
              <Building2 size={16} />
              {!isSidebarCollapsed && <span className="ml-3 font-medium">Franchises</span>}
            </button>

            <button 
              onClick={() => setActiveTab('settings')}
              className={`w-full flex items-center ${isSidebarCollapsed ? 'justify-center p-2' : 'p-2 px-3'} rounded transition-all ${activeTab === 'settings' ? 'bg-zinc-800 text-white shadow-inner' : 'hover:bg-zinc-900/50 text-zinc-500'}`}
              title="Settings"
            >
              <Settings size={16} />
              {!isSidebarCollapsed && <span className="ml-3 font-medium">Settings</span>}
            </button>
          </nav>
        </div>

        <div className="mt-auto border-t border-zinc-800 bg-zinc-950/50">
          <div className={`p-3 ${isSidebarCollapsed ? 'flex justify-center' : ''}`}>
            {!isSidebarCollapsed && (
              <div className="flex items-center gap-3 mb-3">
                <div className="overflow-hidden">
                  <div className="text-[11px] font-bold text-zinc-200 truncate">
                    {session?.user?.email?.split('@')[0]}
                  </div>
                  <div className="text-[9px] text-zinc-500 font-mono uppercase tracking-tight">
                    {currentRole}
                  </div>
                </div>
              </div>
            )}
            
            <button 
              onClick={() => supabase.auth.signOut()} 
              className={`flex items-center text-zinc-500 hover:text-rose-400 transition-colors w-full ${isSidebarCollapsed ? 'justify-center py-2' : 'gap-2 text-[10px] py-1'}`}
            >
              <LogOut size={14} />
              {!isSidebarCollapsed && <span className="font-bold uppercase tracking-wider">Sign Out</span>}
            </button>
          </div>
        </div>
      </aside>

      {/* Main Content */}
      <main className="flex-1 flex flex-col min-w-0">
        
        

        {/* Content Body - Minimal Padding */}
        <div className="flex-1 overflow-auto p-2 lg:p-3 relative">
          <div className="w-full h-full">
            
           {activeTab === 'financials' && (
              <PnLView 
                  allDrivers={simulatedDrivers}
                  drivers={filteredDrivers} 
                  simulationConfig={simulationConfig}
                  setSimulationConfig={setSimulationConfig}
                  fixedExpenses={fixedExpenses}
                  setFixedExpenses={setFixedExpenses}
                  onSaveExpenses={handleSaveExpenses} 
                  finImportData={finImportData}
                  fixedCostsData={fixedCostsData}
                  configContracts={configContracts}
                  setConfigContracts={setConfigContracts}
                  onReady={() => setIsDashboardReady(true)}
                  onDataSync={() => fetchData(true)}
                  globalFilter={globalFilter}
                  setGlobalFilter={setGlobalFilter}
                  currentRole={currentRole}
                />
            )}

            {activeTab === 'drivers' && (
              <div className="flex flex-col h-full">
                <DriverTable drivers={filteredDrivers} />
              </div>
            )}

            {activeTab === 'dispatchers' && (
              <DispatcherTable drivers={filteredDrivers} />
            )}

            {activeTab === 'franchises' && (
              <FranchiseTable drivers={filteredDrivers} simulationConfig={simulationConfig} />
            )}

            {activeTab === 'settings' && (
              <SettingsView onDataSync={() => fetchData(true)} />
            )}
            
          </div>
        </div>
      </main>
    </div>
    </>
  );
};

const App: React.FC = () => {
  const [animDelays] = useState(() => {
    const elapsed = (Date.now() - APP_START_TIME) / 1000;
    return { d10: `-${elapsed % 10}s`, d14: `-${elapsed % 14}s`, d18: `-${elapsed % 18}s` };
  });
  const [session, setSession] = useState<any>(null);
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [authChecking, setAuthChecking] = useState(true);
  const [loginError, setLoginError] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [curtainActive, setCurtainActive] = useState(false);
  const [activeTip, setActiveTip] = useState(() => Math.floor(Math.random() * LOADING_TIPS.length));

  useEffect(() => {
    if (session) return;
    const interval = setInterval(() => {
      setActiveTip(prev => (prev + 1) % LOADING_TIPS.length);
    }, 2500);
    return () => clearInterval(interval);
  }, [session]);

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      setSession(session);
      setAuthChecking(false);
    });

    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {
      if (!session) {
        setCurtainActive(false);
        setLoading(false);
        setSession(null);
      } else {
        setTimeout(() => {
          setSession(session);
        }, 800);
      }
    });

    return () => subscription.unsubscribe();
  }, []);

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setLoginError('');
    setCurtainActive(true);
    
    const { error } = await supabase.auth.signInWithPassword({ email, password });
    if (error) {
      setLoginError(error.message);
      setCurtainActive(false);
      setLoading(false);
    }
  };

  if (authChecking) {
    return <div className="min-h-screen bg-zinc-950 flex flex-col items-center justify-center text-zinc-300">Loading...</div>;
  }

  if (!session) {
    const tips = LOADING_TIPS;

    return (
      <div className="min-h-screen bg-white flex relative overflow-hidden">
        <div className="w-[40%] flex flex-col justify-between px-12 lg:px-20 z-10 bg-white py-12 relative">
          
          <div className="flex-1 flex flex-col justify-center max-w-sm mt-8 relative z-10">
            <div className="mb-10">
              <h1 className="text-4xl font-extrabold text-[#0f172a] tracking-tight mb-3">Access Portal</h1>
              <p className="text-sm text-zinc-500">Sign in to your secure administrative environment.</p>
            </div>
            
            <form onSubmit={handleLogin} className="space-y-6">
              {loginError && (
                <div className="p-3 bg-rose-50 border border-rose-200 rounded-lg text-rose-600 text-xs font-bold text-center">
                  {loginError}
                </div>
              )}
              <div>
                <label className="block text-xs font-bold text-[#334155] mb-2 uppercase tracking-wide">Email Address</label>
                <input type="email" value={email} onChange={e => setEmail(e.target.value)} className="w-full bg-white border border-zinc-200 text-sm text-[#0f172a] rounded-lg px-4 py-3 focus:border-zinc-400 focus:ring-1 focus:ring-zinc-400 outline-none transition-all placeholder:text-zinc-400 shadow-sm" placeholder="admin@pnl.com" required disabled={curtainActive} />
              </div>
              <div>
                <label className="block text-xs font-bold text-[#334155] mb-2 uppercase tracking-wide">Password</label>
                <div className="relative">
                  <input type={showPassword ? "text" : "password"} value={password} onChange={e => setPassword(e.target.value)} className="w-full bg-white border border-zinc-200 text-sm text-[#0f172a] rounded-lg px-4 py-3 pr-10 focus:border-zinc-400 focus:ring-1 focus:ring-zinc-400 outline-none transition-all placeholder:text-zinc-400 shadow-sm" placeholder="••••••••" required disabled={curtainActive} />
                  <button type="button" onClick={() => setShowPassword(!showPassword)} className="absolute right-3 top-1/2 -translate-y-1/2 text-zinc-400 hover:text-zinc-600 transition-colors flex items-center justify-center">
                    {showPassword ? <EyeOff size={16} /> : <Eye size={16} />}
                  </button>
                </div>
              </div>
              <button type="submit" disabled={loading || curtainActive} className="w-full bg-[#111827] hover:bg-zinc-800 text-white text-sm font-semibold py-3.5 rounded-lg transition-all mt-6 shadow-md disabled:opacity-50 flex justify-center items-center gap-3">
                {loading ? 'Authenticating...' : 'Secure Sign In'}
                {!loading && <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12h14M12 5l7 7-7 7"/></svg>}
              </button>
            </form>
          </div>

          <div className="text-[10px] text-zinc-400 font-medium tracking-wide relative z-10">
            © 2026 PnL Portal. All rights reserved.<br/>
            Version 4.0.1 • Enterprise Edition
          </div>
        </div>

        <div 
          className={`absolute right-0 top-0 h-full flex flex-col items-center justify-center transition-all duration-[800ms] ease-[cubic-bezier(0.87,0,0.13,1)] z-20 ${curtainActive ? 'w-full border-l-0' : 'w-[60%] border-l border-emerald-500/30'} bg-gradient-to-br from-black via-[#020a06] to-black overflow-hidden`}
        >
          <div className="absolute inset-0 bg-[linear-gradient(to_right,#10b98108_1px,transparent_1px),linear-gradient(to_bottom,#10b98108_1px,transparent_1px)] bg-[size:40px_40px]"></div>
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[900px] h-[900px] bg-emerald-800/15 rounded-full blur-[150px] pointer-events-none"></div>
          <div className="absolute top-[5%] left-[5%] w-[600px] h-[600px] bg-purple-700/15 rounded-full blur-[120px] pointer-events-none"></div>
          <div className="absolute bottom-[5%] right-[5%] w-[600px] h-[600px] bg-blue-700/15 rounded-full blur-[120px] pointer-events-none"></div>

          <div className={`relative flex items-center justify-center transition-all duration-[800ms] ${curtainActive ? 'mb-16' : 'mb-12'} w-64 h-64`}>
             <div className="absolute inset-6 bg-emerald-500/5 rounded-full blur-2xl animate-pulse"></div>
             <div className="absolute inset-0 border-[2px] border-emerald-500/10 border-t-emerald-500/80 border-b-emerald-500/80 rounded-[2rem] animate-[spin_10s_linear_infinite]" style={{ animationDelay: animDelays.d10 }}></div>
             <div className="absolute inset-3 border-[2px] border-blue-500/10 border-l-blue-500/80 border-r-blue-500/80 rounded-3xl animate-[spin_14s_linear_infinite_reverse]" style={{ animationDelay: animDelays.d14 }}></div>
             <div className="absolute inset-6 border-[2px] border-indigo-500/10 border-t-indigo-500/80 border-b-indigo-500/80 rounded-2xl animate-[spin_18s_linear_infinite]" style={{ animationDelay: animDelays.d18 }}></div>
             <img src="https://i.postimg.cc/ryjhgvGq/Default-Make-a-logo-for-Profit-and-Loss-application-portal-It-2-a128667d-b54d-44ca-bb4d-32ac1ddb5c95.png" alt="PnL Logo" className="w-48 h-48 object-contain drop-shadow-[0_0_30px_rgba(16,185,129,0.4)] z-10" referrerPolicy="no-referrer" />
          </div>

          <div className={`flex flex-col items-center relative z-10 mb-4 ${curtainActive ? 'hidden' : ''}`}>
            <h1 className="text-4xl font-bold text-white tracking-[0.15em] mb-3 font-mono uppercase text-center drop-shadow-md">Financial Intelligence</h1>
            <h2 className="text-xs text-emerald-400 tracking-[0.4em] uppercase text-center font-semibold">Platform</h2>
          </div>
          
          <div className={`max-w-md text-center px-6 mt-6 mb-12 ${curtainActive ? 'hidden' : ''}`}>
            <p className="text-zinc-400 text-sm leading-relaxed font-light">
              Enterprise-grade portal for mastering your fleet's financial performance. Execute automated PnL splits, run revenue simulations, and track fleet expenses with precision.
            </p>
          </div>

          <div className={`transition-all duration-500 w-[500px] z-10 ${curtainActive ? 'opacity-100 delay-300 mb-12' : 'opacity-0 absolute pointer-events-none mb-12'}`}>
            <div className="flex justify-between items-end mb-3 font-mono text-[10px] tracking-[0.2em] text-emerald-500/70">
              <span className="text-emerald-500/60 font-bold uppercase">Loading...</span>
              <span className="text-emerald-400 text-xl font-medium leading-none">0<span className="text-emerald-500/50 text-sm">%</span></span>
            </div>
            <div className="flex gap-1 h-2">
              {Array.from({ length: 40 }).map((_, i) => (
                <div key={i} className="h-full flex-1 rounded-sm bg-zinc-800/40" />
              ))}
            </div>
          </div>

          <div className={`absolute bottom-16 w-3/4 max-w-lg text-center transition-all duration-500 z-10 ${curtainActive ? 'opacity-100 delay-300' : 'opacity-0 pointer-events-none'}`}>
            <div className="h-12 text-sm text-zinc-400 font-light tracking-wide px-4 leading-relaxed">"{tips[activeTip]}"</div>
            <div className="flex justify-center gap-2.5 mt-8">
              {tips.map((_, idx) => (
                <div key={idx} className={`w-1.5 h-1.5 rounded-full transition-all duration-500 ${activeTip === idx ? 'bg-emerald-400 w-8 shadow-[0_0_8px_#34d399]' : 'bg-zinc-800'}`} />
              ))}
            </div>
          </div>
        </div>
      </div>
    );
  }

 return (
    <ErrorBoundary>
      <AppContent session={session} />
    </ErrorBoundary>
  );
};

export default App;